[package]
name = "sukebe"
version = "0.1.0"
authors = ["Alex Nørgaard <Umbra@AbstractUmbra.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false}
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.125", features = ["derive"] }
